
from enum import Enum
class OrderState(str,Enum):
    CREATED="CREATED"; PENDING_SUBMIT="PENDING_SUBMIT"; SUBMITTED="SUBMITTED"
    PARTIALLY_FILLED="PARTIALLY_FILLED"; FILLED="FILLED"; CANCEL_PENDING="CANCEL_PENDING"
    CANCELLED="CANCELLED"; REJECTED="REJECTED"; EXPIRED="EXPIRED"

VALID={
"CREATED": {"PENDING_SUBMIT","REJECTED"},
"PENDING_SUBMIT":{"SUBMITTED","REJECTED"},
"SUBMITTED":{"PARTIALLY_FILLED","FILLED","CANCEL_PENDING","CANCELLED","REJECTED","EXPIRED"},
"PARTIALLY_FILLED":{"PARTIALLY_FILLED","FILLED","CANCEL_PENDING","CANCELLED","REJECTED"},
"CANCEL_PENDING":{"CANCELLED","FILLED","PARTIALLY_FILLED"},
"FILLED":set(),"CANCELLED":set(),"REJECTED":set(),"EXPIRED":set()
}
def transition(current,new):
    if new not in VALID[current]: raise ValueError(f"invalid order transition {current}->{new}")
    return new
